[package]
name = "maf_cal"
description = "A tool to calibrate a Mass Airflow sensor"
version = "0.1.1"
edition = "2021"
license = "GPL-3.0-or-later"
authors = ["Kyle Simmons", "Max Madden"]

[dependencies]
csv = "1.2.2"